
export REGIONS_ONE="ACAd ACAv AId AIp AIv AUDd AUDp AUDv ECT FRP GU ILA MOp MOs ORBl"
export REGIONS_TWO="ORBm ORBvl PERI PL RSPagl RSPd RSPv TEa"
export REGIONS_THREE="SSp-ll SSp-m SSp-n SSp-tr SSp-ul SSp-un SSs"
export REGIONS_FOUR="VISC VISa VISal VISam VISl VISli VISp VISpl VISpm VISpor VISrl"
