"""A base class describing the behavior of a parameter.Generator"""
from abc import ABC, abstractmethod
from dmt.vtk.measurement.parameter import Parameter
from dmt.vtk.utils.descriptor import ClassAttribute, Field

class ParamGenerator(ABC):
    """Base class describing the behavior of a Parameter Generator."""

    parameter = ClassAttribute(
        __name__ = "parameter",
        __type__ = Parameter,
        __doc__  = """Parameter generated by this ParamGenerator."""
    )
    def __init__(self, *args, **kwargs):
        """..."""
        pass

    @abstractmethod
    def random_grouped_values(self, value, ):
        """Values of self.parameter, ordered randomly."""
        pass

