"""A random parameter is just another parameter that can generate
random values."""

from abc import abstractmethod
from dmt.vtk.utils.descriptor import Field
#from dmt.vtk.measurement.parameter import Parameter

class RandomParameter:
    """A parameter that yields random values.
    Not much here. Will be used as a tag to say that a
    Parameter is a RandomParameter."""
    value_type = Field(
        __name__ = "value_type",
        __type__ = type,
        __doc__  = """Type of the variable generated by this RandomParameter."""
    )
    @abstractmethod
    def random_values(*args, **kwargs):
        pass
